"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "vi" | "en" | "zh"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  vi: {
    "header.home": "Trang chủ",
    "header.contact": "Liên hệ",
    "header.about": "Thông tin",
    "home.title": "VietGuardScan",
    "home.subtitle": "Quét và Đánh giá An ninh Ứng dụng APK",
    "home.upload": "Tải file APK lên",
    "home.scan": "Quét",
    "home.dragdrop": "Kéo thả file APK hoặc nhấp để chọn",
    "home.reportNote": "Báo cáo sẽ được gửi về email của bạn",
    "charts.title": "Thống kê Quét APK",
    "charts.scannedApps": "Ứng dụng đã quét",
    "charts.vulnerabilities": "Phân bố Lỗ hổng Bảo mật",
    "charts.appCategories": "Phân loại Ứng dụng",
    "charts.critical": "Nghiêm trọng",
    "charts.high": "Cao",
    "charts.medium": "Trung bình",
    "charts.low": "Thấp",
    "charts.finance": "Tài chính",
    "charts.government": "Hành chính công",
    "charts.entertainment": "Giải trí",
    "charts.gaming": "Game",
    "charts.social": "Mạng xã hội",
    "charts.productivity": "Năng suất",
    "charts.other": "Khác",
    "form.email": "Email",
    "form.sendOtp": "Gửi OTP",
    "form.otp": "Mã OTP",
    "form.verifyOtp": "Xác thực",
    "form.fullname": "Họ và tên",
    "form.company": "Tên công ty",
    "form.phone": "Số điện thoại",
    "form.notes": "Ghi chú",
    "form.requirements": "Nhu cầu",
    "form.submit": "Gửi",
    "form.cancel": "Hủy",
    "form.scanInfo": "Thông tin quét",
    "form.emailVerified": "Email đã được xác thực",
    "success.message": "Chúng tôi sẽ quét và gửi báo cáo cho bạn sau ít phút",
    "success.uploadAnother": "Tải file khác",
    "contact.title": "Liên hệ với chúng tôi",
    "contact.description": "Hãy liên hệ với chúng tôi để được hỗ trợ hoặc tư vấn",
    "contact.email": "Email",
    "contact.phone": "Điện thoại",
    "contact.address": "Địa chỉ",
    "contact.name": "Họ tên",
    "contact.subject": "Tiêu đề",
    "contact.message": "Tin nhắn",
    "contact.send": "Gửi tin nhắn",
    "about.title": "Về VietGuardScan",
    "about.description": "Nền tảng quét an ninh APK hàng đầu tại Việt Nam",
    "about.mission": "Sứ mệnh của chúng tôi",
    "about.missionText":
      "VietGuardScan cam kết cung cấp phân tích bảo mật toàn diện cho các ứng dụng Android. Chúng tôi giúp các nhà phát triển, nhà nghiên cứu bảo mật và các tổ chức xác định các lỗ hổng và đảm bảo ứng dụng của họ đáp ứng các tiêu chuẩn bảo mật cao nhất.",
    "about.securityFirst": "Bảo mật trên hết",
    "about.securityText": "Phân tích bảo mật nâng cao với khả năng phát hiện hàng đầu trong ngành",
    "about.fastReliable": "Nhanh chóng & Đáng tin cậy",
    "about.fastText": "Quét nhanh với kết quả chính xác và báo cáo chi tiết",
    "about.expertSupport": "Hỗ trợ chuyên gia",
    "about.expertText": "Đội ngũ chuyên gia sẵn sàng hỗ trợ nhu cầu bảo mật của bạn",
    "about.team": "Đội ngũ của chúng tôi",
    "about.teamText":
      "Đội ngũ của chúng tôi bao gồm các chuyên gia bảo mật, nhà phát triển và nhà nghiên cứu có kinh nghiệm, cam kết làm cho bảo mật Android dễ tiếp cận và toàn diện cho mọi người.",
    "footer.company": "CÔNG TY CỔ PHẦN AN NINH MẠNG QUỐC TẾ",
    "footer.office": "Văn phòng: TT3-5 Khu đô thị Đại Kim mới, Định Công, Hà Nội",
    "footer.phone": "Điện thoại: 0931.487.231",
    "footer.hotline": "Hotline: 0707.806.860",
    "footer.email": "E-mail: info@icss.com.vn",
    "footer.website": "www.icss.com.vn",
    "footer.connect": "Kết nối tới ICSS",
    "footer.products": "Sản phẩm",
    "footer.oracle": "Oracle",
    "footer.vietguard": "VietGuard",
    "footer.dashboard": "Dashboard",
  },
  en: {
    "header.home": "Home",
    "header.contact": "Contact",
    "header.about": "About",
    "home.title": "VietGuardScan",
    "home.subtitle": "APK Security Scanning & Analysis",
    "home.upload": "Upload APK File",
    "home.scan": "Scan",
    "home.dragdrop": "Drag and drop APK file or click to select",
    "home.reportNote": "Report will be sent to your email",
    "charts.title": "APK Scanning Statistics",
    "charts.scannedApps": "Apps Scanned",
    "charts.vulnerabilities": "Security Vulnerabilities Distribution",
    "charts.appCategories": "App Categories",
    "charts.critical": "Critical",
    "charts.high": "High",
    "charts.medium": "Medium",
    "charts.low": "Low",
    "charts.finance": "Finance",
    "charts.government": "Government",
    "charts.entertainment": "Entertainment",
    "charts.gaming": "Gaming",
    "charts.social": "Social Media",
    "charts.productivity": "Productivity",
    "charts.other": "Other",
    "form.email": "Email",
    "form.sendOtp": "Send OTP",
    "form.otp": "OTP Code",
    "form.verifyOtp": "Verify",
    "form.fullname": "Full Name",
    "form.company": "Company Name",
    "form.phone": "Phone Number",
    "form.notes": "Notes",
    "form.requirements": "Requirements",
    "form.submit": "Submit",
    "form.cancel": "Cancel",
    "form.scanInfo": "Scan Information",
    "form.emailVerified": "Email verified",
    "success.message": "We will scan and send the report to you in a few minutes",
    "success.uploadAnother": "Upload Another File",
    "contact.title": "Contact Us",
    "contact.description": "Get in touch with our team for any inquiries or support",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.name": "Name",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "about.title": "About VietGuardScan",
    "about.description": "Leading APK security scanning platform in Vietnam",
    "about.mission": "Our Mission",
    "about.missionText":
      "VietGuardScan is dedicated to providing comprehensive security analysis for Android applications. We help developers, security researchers, and organizations identify vulnerabilities and ensure their applications meet the highest security standards.",
    "about.securityFirst": "Security First",
    "about.securityText": "Advanced security analysis with industry-leading detection capabilities",
    "about.fastReliable": "Fast & Reliable",
    "about.fastText": "Quick scanning with accurate results and detailed reports",
    "about.expertSupport": "Expert Support",
    "about.expertText": "Professional team ready to assist with your security needs",
    "about.team": "Our Team",
    "about.teamText":
      "Our team consists of experienced security professionals, developers, and researchers dedicated to making Android security accessible and comprehensive for everyone.",
    "footer.company": "INTERNATIONAL CYBERSECURITY COMPANY",
    "footer.office": "Office: TT3-5 Dai Kim New Urban Area, Dinh Cong, Hanoi",
    "footer.phone": "Phone: 0931.487.231",
    "footer.hotline": "Hotline: 0707.806.860",
    "footer.email": "E-mail: info@icss.com.vn",
    "footer.website": "www.icss.com.vn",
    "footer.connect": "Connect to ICSS",
    "footer.products": "Products",
    "footer.oracle": "Oracle",
    "footer.vietguard": "VietGuard",
    "footer.dashboard": "Dashboard",
  },
  zh: {
    "header.home": "首页",
    "header.contact": "联系",
    "header.about": "关于",
    "home.title": "VietGuardScan",
    "home.subtitle": "APK安全扫描和分析",
    "home.upload": "上传APK文件",
    "home.scan": "扫描",
    "home.dragdrop": "拖放APK文件或点击选择",
    "home.reportNote": "报告将发送到您的电子邮件",
    "charts.title": "APK扫描统计",
    "charts.scannedApps": "已扫描应用",
    "charts.vulnerabilities": "安全漏洞分布",
    "charts.appCategories": "应用分类",
    "charts.critical": "严重",
    "charts.high": "高",
    "charts.medium": "中等",
    "charts.low": "低",
    "charts.finance": "金融",
    "charts.government": "政府",
    "charts.entertainment": "娱乐",
    "charts.gaming": "游戏",
    "charts.social": "社交媒体",
    "charts.productivity": "生产力",
    "charts.other": "其他",
    "form.email": "电子邮件",
    "form.sendOtp": "发送OTP",
    "form.otp": "OTP代码",
    "form.verifyOtp": "验证",
    "form.fullname": "全名",
    "form.company": "公司名称",
    "form.phone": "电话号码",
    "form.notes": "备注",
    "form.requirements": "需求",
    "form.submit": "提交",
    "form.cancel": "取消",
    "form.scanInfo": "扫描信息",
    "form.emailVerified": "电子邮件已验证",
    "success.message": "我们将在几分钟内扫描并向您发送报告",
    "success.uploadAnother": "上传另一个文件",
    "contact.title": "联系我们",
    "contact.description": "与我们的团队联系以获取任何询问或支持",
    "contact.email": "电子邮件",
    "contact.phone": "电话",
    "contact.address": "地址",
    "contact.name": "名字",
    "contact.subject": "主题",
    "contact.message": "消息",
    "contact.send": "发送消息",
    "about.title": "关于VietGuardScan",
    "about.description": "越南领先的APK安全扫描平台",
    "about.mission": "我们的使命",
    "about.missionText":
      "VietGuardScan致力于为Android应用程序提供全面的安全分析。我们帮助开发人员、安全研究人员和组织识别漏洞并确保其应用程序符合最高安全标准。",
    "about.securityFirst": "安全第一",
    "about.securityText": "具有业界领先检测能力的高级安全分析",
    "about.fastReliable": "快速可靠",
    "about.fastText": "快速扫描，准确结果和详细报告",
    "about.expertSupport": "专家支持",
    "about.expertText": "专业团队随时准备协助您的安全需求",
    "about.team": "我们的团队",
    "about.teamText":
      "我们的团队由经验丰富的安全专业人员、开发人员和研究人员组成，致力于为所有人提供易于访问和全面的Android安全。",
    "footer.company": "国际网络安全公司",
    "footer.office": "办公室：河内定公大金新城市区TT3-5",
    "footer.phone": "电话：0931.487.231",
    "footer.hotline": "热线：0707.806.860",
    "footer.email": "电子邮件：info@icss.com.vn",
    "footer.website": "www.icss.com.vn",
    "footer.connect": "连接到ICSS",
    "footer.products": "产品",
    "footer.oracle": "Oracle",
    "footer.vietguard": "VietGuard",
    "footer.dashboard": "仪表板",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("vi")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["vi"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
